const settings = {
  startingLives: 10,
  startingMoney: 10,
  startingLexiconSize: 3,
  startingShopSize: 3,
  lexiconIncrementSize: 1,
  shopIncrementSize: 1,
  maxSize: 15, // The scrabble board is 15 by 15
  randomMultiplier: 2,
  numWords: 279495,
  letter: {
    a: { dmg: 1, hp: 1 },
    b: { dmg: 1, hp: 1 },
    c: { dmg: 1, hp: 1 },
    e: { dmg: 1, hp: 1 },
    f: { dmg: 1, hp: 1 },
    g: { dmg: 1, hp: 1 },
    h: { dmg: 1, hp: 1 },
    i: { dmg: 1, hp: 1 },
    j: { dmg: 1, hp: 1 },
    k: { dmg: 100, hp: 100 },
    l: { dmg: 1, hp: 1 },
    m: { dmg: 1, hp: 1 },
    n: { dmg: 1, hp: 1 },
    o: { dmg: 1, hp: 1 },
    p: { dmg: 1, hp: 1 },
    q: { dmg: 1, hp: 1 },
    r: { dmg: 1, hp: 1 },
    s: { dmg: 1, hp: 1 },
    t: { dmg: 1, hp: 1 },
    u: { dmg: 1, hp: 1 },
    v: { dmg: 1, hp: 1 },
    w: { dmg: 1, hp: 1 },
    x: { dmg: 1, hp: 1 },
    y: { dmg: 1, hp: 1 },
    z: { dmg: 1, hp: 1 },
  },
};

export default settings;
